### ISSUE TITLE
Propensity scores for multinomial PS

### ISSUE THREAD

**Issue by andrewjmc** [ngreifer/WeightIt#20]
I can't find PS in the covariates table of the weightit object for CBPS PS weighting.

Is there anywhere else to get them? I would like to assess overlap.

Thanks!

**Comment by ngreifer** [comment]
See #3. For multinomial treatments, the PS for each individual is a vector with a value for each treatment option, not a single number. When using several methods, the values in this vector are not guaranteed to sum to 1, so they are not valid propensity scores anyway. They are just used to compute the weights. For this reason, I don't include them in the output. You can extract them yourself by setting `include.obj = TRUE` in the call to `weightit()` and getting them from the original fit object. How this is done depends on how many treatment categories there are and the estimand you chose. You can use the code in `weightit2cbps()` to see how to get the predicted probabilities from this object.

In my opinion, there is no use for these propensity scores once you have computed the weights. I disagree with the use of estimated propensity scores to assess overlap.

**Comment by andrewjmc** [comment]
OK, fascinating and helpful. Thanks!

I had always wondered about the emphasis on PS overlap, given the primary importance of covariates.

Cheeky partly related question -- if testing several outcomes, each of which are missing in a small proportion (and not in a position to impute), and with some outcomes only relevant to subgroups. Would you then advocate CBPS weighting on the population for each outcome set (even if small) rather than a single set of CBPS weights to "rule them all" (with only the weights corresponding to outcomes being present).

**Comment by ngreifer** [comment]
I would say that if some outcomes are only relevant to certain subgroups, to do the analyses in those subgroups independently. E.g., if you're studying the effect of some health behavior on prostate and ovarian cancers, you would do analyses separately within prostate-havers and ovary-havers, rather than a single analysis that balances all patients across the treatment groups regardless of their eligibility for the outcome. I'm not totally sure what you mean about the missingness or how that relates to weighting, unless you're weighting as an alternative to MI in addition to weighting for covariate imbalance across treatment levels. That's a bit of a harder issue that I don't know much about (although I am writing a paper about it with someone). If your missingness is small, you can often do casewise deletion or single imputation without much trouble.
