### ISSUE TITLE
Estimand default

### ISSUE THREAD

**Issue by statzhero** [ngreifer/WeightIt#42]
This is sort of a silly questions but why is the default for the `weightit()` estimand argument "ATE" and not "ATT"?

**Comment by ngreifer** [comment]
A few reasons. It's the default in `twang`. It's also the estimand people most frequently use IPW for. Since at the time `MatchIt` could only target the ATT, I wanted to demonstrate `WeightIt` as a method for estimating other estimands, and to get people to be thinking about estimands rather than just use the default if they wanted to compare matching and weighting. It was kind of an arbitrary choice, though.
