### ISSUE TITLE
Sampling weights: to trim or not to trim

### ISSUE THREAD

**Issue by lorenzoFabbri** [ngreifer/WeightIt#55]
This is another mostly conceptual question, and not a bug/issue with the package.

I am doing sensitivity analysis on a small subset of my sample. I thus decided to estimate the weights to reduce the effects of any selection bias:
```
selection ~ covariates
```
where `selction` is a indicator variable which is 1 when the subject was indeed selected into the subset, 0 otherwise. I then pass the `weights` from the call to `WeightIt::weightit` to `s.weights` when estimating the actual balancing weights.

I was wondering whether it is *better* to eventually trim the weights for selection bias, or if it is *better* to pass them as is to the second step and then trim these final balancing weights. I know I can check the summary and see whether there are extreme weights, but I was looking for a more conceptual understanding. Thank you.

**Comment by ngreifer** [comment]
I assume by trimming you mean setting extreme weights to a less extreme value. If so, that is just a modeling decision, no different from choosing probit vs logit regression. So you can trim at any point in the analysis, just the same as you would by choosing a different model. Do whatever it takes to achieve balance and a high ESS. There are no rules otherwise.
