### ISSUE TITLE
WeightItMSM only "ATE"? 

### ISSUE THREAD

**Issue by mkrasmus** [ngreifer/WeightIt#57]
Hi Noah many thanks for maintaining this package, very grateful it exists. I have a question regarding MSMs and ATE/ATT and the current functionality of WeightItMSM. The reference material on the [website ](https://ngreifer.github.io/WeightIt/reference/weightitMSM.html) states that for the estimand: ""ATE", currently the only estimand for MSMs with binary or multi-category treatments." I was wondering if this is true for the MSM approach in general, or if it just a reflection of the WeightItMSM package in its current version? I was hoping to find an R package for MSM that yields ATT estimand and I think I might need to use the twang package's iptw function for this, but a little unsure on what is possible with MSM and ATT given that statement.

**Comment by ngreifer** [comment]
If you can find any description of MSMs for the ATT, I will happily look into implementing it :) But as far as I am concerned, the estimand isn't well defined for MSMs. So the fact that it would be possible to do with `twang::iptw()` is an error, not an advantage. You should not attempt this method without a theoretical understanding of whether it is possible. Again, if you find a reference for the ATT in this context, please let me know, as I would love to implement this in `WeightIt`. It could be as simple as multiplying ATT weights at each time point (in which case you can already do this by calling `weightit()` once per time point and multiplying the weights yourself, which is all `weightitMSM()` does), but it might be a lot more complicated than that. I'm working on a massive update to `WeightIt` so if you can find a reference for the method it would be a cool thing to add.

**Comment by mkrasmus** [comment]
Sorry for delayed response. I was aware of just this one example "Doubly Robust Estimation of Average Treatment Effects on the Treated through Marginal Structural Models" https://doi.org/10.1353/obs.2023.0025 . But this appears to be more how-to and I'm not sure if the theoretical consideration is addressed. But if there is something here then at least there is sufficient code and a generous repo: https://github.com/PFMB/causalchall

**Comment by ngreifer** [comment]
Yes, I did come across that paper, but it doesn't describe a methodology for estimating the ATT using weighting for MSMs. TMLE is a fundamentally different method since no weights are estimated. In the same way weighting for MSMs cannot be used to assess effect modification by time-varying confounders, I have doubts that it can be used to estimate the ATT because doing so involves conditioning on a time-varying variable (the treatment). In contrast, G-computation (and TMLE, which is just G-computation with a correction) can be used to assess effect modification by time-varying confounders because it doesn't directly condition on the confounders. So although the paper you linked to describes the estimand and one method of estimating it, I am still not convinced that there is a method that relies on weighting alone to target the ATT. Again, if you do find such a method, please send it along as this would be a useful addition to `WeightIt`.
