### ISSUE TITLE
F statistic and r squared for lm_weightit() and glm_weightit()?

### ISSUE THREAD

**Issue by jfordal** [ngreifer/WeightIt#59]
I am a grad student using WeightIt for the first time and noticed that the summary output for the lm_weightit () and glm_weightit() functions does not include the F statistic/r squared/adj. r squared. I am using g-computation and reporting only those results (e.g. not interpreting the coefficients of the outcome model itself); however, I would still be interested to see these for the models after weighting.

Thank you in advance, and also for developing such a great package.

**Comment by ngreifer** [comment]
I don't provide this info because I don't think it has any valid statistical use. I'm glad you're not reporting it, but I would need to be convinced of its utility at all to be included in `WeightIt`. I will tell you how to get that info, though, since it isn't reported.

To get the omnibus F-statistic, you can run a joint test on all the coefficients other than the intercept. The F-statistic tests whether all coefficients in the model are equal to 0. `marginaleffects::hypotheses()` can do this, as does `car::lht()`. You can also do this manually using the coefficients and asymptotic covariance matrix. A reason I don't think you should do this is that this involves testing whether covariate coefficients differ from 0, but that is not a relevant test (i.e., the covariate coefficients don't have any meaningful interpretation and their inclusion in the outcome model should not be based on significance).

To get the R2, just re-fit the model using `lm()` with `weights = w.out$weights`. None of the tests or standard errors should be interpreted, but the model R2 is the same as would be computed by `lm_weightit()`, since the latter calls `lm()` under the hood anyway.

Thank you for the kind words!

**Comment by ngreifer** [comment]
You should not compare models using adjusted R2 to decide how to model the outcome; doing so invalidates your statistical inference. Just use the fully interacted model. How well the covariates are balanced has nothing to do with the significance of covariates in the outcome model or their interaction with the treatment. The absence of interactions with the treatment suggests that the treatment effect does not vary across levels of the covariate. But it is critical to remember that the outcome model is completely uninterpretable; its sole purpose is to increase the precision of the effect estimate. If you want to test for the presence of effect modification by the covariates, you need to design a study and analysis specifically aimed at testing that.

I read the section in that textbook and I have to say it is complete nonsense. You should absolutely include the pre-test measure of the outcome both in the propensity score model and the outcome model. It is clearly one of the most important confounders to adjust for, and you should never include a variable in the outcome model that is not adjusted for in the propensity score model. The author does not cite any sources in making that claim and it reveals a fundamental misunderstanding of what covariate adjustment is and how it works.
